// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_service.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	domain "ms-notification/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmail is a mock of Email interface.
type MockEmail struct {
	ctrl     *gomock.Controller
	recorder *MockEmailMockRecorder
	isgomock struct{}
}

// MockEmailMockRecorder is the mock recorder for MockEmail.
type MockEmailMockRecorder struct {
	mock *MockEmail
}

// NewMockEmail creates a new mock instance.
func NewMockEmail(ctrl *gomock.Controller) *MockEmail {
	mock := &MockEmail{ctrl: ctrl}
	mock.recorder = &MockEmailMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmail) EXPECT() *MockEmailMockRecorder {
	return m.recorder
}

// SendConfirmationEmail mocks base method.
func (m *MockEmail) SendConfirmationEmail(arg0 domain.ConfirmationEmailInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendConfirmationEmail", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendConfirmationEmail indicates an expected call of SendConfirmationEmail.
func (mr *MockEmailMockRecorder) SendConfirmationEmail(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendConfirmationEmail", reflect.TypeOf((*MockEmail)(nil).SendConfirmationEmail), arg0)
}

// SendWeatherForecastDailyEmail mocks base method.
func (m *MockEmail) SendWeatherForecastDailyEmail(arg0 domain.WeatherForecastEmailInput[*domain.DayWeather]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWeatherForecastDailyEmail", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWeatherForecastDailyEmail indicates an expected call of SendWeatherForecastDailyEmail.
func (mr *MockEmailMockRecorder) SendWeatherForecastDailyEmail(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWeatherForecastDailyEmail", reflect.TypeOf((*MockEmail)(nil).SendWeatherForecastDailyEmail), arg0)
}

// SendWeatherForecastHourlyEmail mocks base method.
func (m *MockEmail) SendWeatherForecastHourlyEmail(arg0 domain.WeatherForecastEmailInput[*domain.Weather]) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWeatherForecastHourlyEmail", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWeatherForecastHourlyEmail indicates an expected call of SendWeatherForecastHourlyEmail.
func (mr *MockEmailMockRecorder) SendWeatherForecastHourlyEmail(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWeatherForecastHourlyEmail", reflect.TypeOf((*MockEmail)(nil).SendWeatherForecastHourlyEmail), arg0)
}
