services:
  db_test:
    image: postgres:16
    container_name: weather_forecast_sub_postgres_test
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d weather_forecast_sub_go_test'" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather_forecast_sub_go_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
  redis_test:
    image: redis:latest
    container_name: weather_forecast_sub_redis_test
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "6378:6379"

volumes:
  postgres_test_data:
