http_server:
  host: localhost
  port: 8080
  readTimeout: 10s
  readHeaderTimeout: 5s
  writeTimeout: 10s

db:
  migrationsPath: "file://../migrations"

smtp:
  host: "smtp.ukr.net"
  port: 465
  from: "weather_forecast_sub@ukr.net"
  from_name: "Weather Forecast"

email:
  templates:
    confirmation_email: "../templates/email/confirmation_email.html"
    weather_forecast_daily: "../templates/email/weather_forecast_daily.html"
    weather_forecast_hourly: "../templates/email/weather_forecast_hourly.html"
  subjects:
    confirmation_email: "Confirm your email"
    weather_forecast: "%s weather forecast"