// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: notification.proto

package notificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Subscription info
type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

func (x *Subscription) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Subscription) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Subscription) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Current Weather data
type Weather struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Temperature   float32                `protobuf:"fixed32,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity      float32                `protobuf:"fixed32,2,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Weather) Reset() {
	*x = Weather{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Weather) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Weather) ProtoMessage() {}

func (x *Weather) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Weather.ProtoReflect.Descriptor instead.
func (*Weather) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

func (x *Weather) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *Weather) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *Weather) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Daily Weather data
type DayWeather struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SevenAm       *Weather               `protobuf:"bytes,1,opt,name=seven_am,json=sevenAm,proto3" json:"seven_am,omitempty"`
	TenAm         *Weather               `protobuf:"bytes,2,opt,name=ten_am,json=tenAm,proto3" json:"ten_am,omitempty"`
	OnePm         *Weather               `protobuf:"bytes,3,opt,name=one_pm,json=onePm,proto3" json:"one_pm,omitempty"`
	FourPm        *Weather               `protobuf:"bytes,4,opt,name=four_pm,json=fourPm,proto3" json:"four_pm,omitempty"`
	SevenPm       *Weather               `protobuf:"bytes,5,opt,name=seven_pm,json=sevenPm,proto3" json:"seven_pm,omitempty"`
	TenPm         *Weather               `protobuf:"bytes,6,opt,name=ten_pm,json=tenPm,proto3" json:"ten_pm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DayWeather) Reset() {
	*x = DayWeather{}
	mi := &file_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DayWeather) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayWeather) ProtoMessage() {}

func (x *DayWeather) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayWeather.ProtoReflect.Descriptor instead.
func (*DayWeather) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

func (x *DayWeather) GetSevenAm() *Weather {
	if x != nil {
		return x.SevenAm
	}
	return nil
}

func (x *DayWeather) GetTenAm() *Weather {
	if x != nil {
		return x.TenAm
	}
	return nil
}

func (x *DayWeather) GetOnePm() *Weather {
	if x != nil {
		return x.OnePm
	}
	return nil
}

func (x *DayWeather) GetFourPm() *Weather {
	if x != nil {
		return x.FourPm
	}
	return nil
}

func (x *DayWeather) GetSevenPm() *Weather {
	if x != nil {
		return x.SevenPm
	}
	return nil
}

func (x *DayWeather) GetTenPm() *Weather {
	if x != nil {
		return x.TenPm
	}
	return nil
}

// Confirmation Email
type ConfirmationEmailRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Email            string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	ConfirmationLink string                 `protobuf:"bytes,2,opt,name=confirmation_link,json=confirmationLink,proto3" json:"confirmation_link,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConfirmationEmailRequest) Reset() {
	*x = ConfirmationEmailRequest{}
	mi := &file_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmationEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmationEmailRequest) ProtoMessage() {}

func (x *ConfirmationEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmationEmailRequest.ProtoReflect.Descriptor instead.
func (*ConfirmationEmailRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmationEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ConfirmationEmailRequest) GetConfirmationLink() string {
	if x != nil {
		return x.ConfirmationLink
	}
	return ""
}

type SendStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendStatus) Reset() {
	*x = SendStatus{}
	mi := &file_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendStatus) ProtoMessage() {}

func (x *SendStatus) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendStatus.ProtoReflect.Descriptor instead.
func (*SendStatus) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{4}
}

func (x *SendStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Daily Forecast Email
type DailyForecastEmailRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Subscription    *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Weather         *DayWeather            `protobuf:"bytes,2,opt,name=weather,proto3" json:"weather,omitempty"`
	Date            string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	UnsubscribeLink string                 `protobuf:"bytes,4,opt,name=unsubscribe_link,json=unsubscribeLink,proto3" json:"unsubscribe_link,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DailyForecastEmailRequest) Reset() {
	*x = DailyForecastEmailRequest{}
	mi := &file_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyForecastEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyForecastEmailRequest) ProtoMessage() {}

func (x *DailyForecastEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyForecastEmailRequest.ProtoReflect.Descriptor instead.
func (*DailyForecastEmailRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{5}
}

func (x *DailyForecastEmailRequest) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *DailyForecastEmailRequest) GetWeather() *DayWeather {
	if x != nil {
		return x.Weather
	}
	return nil
}

func (x *DailyForecastEmailRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyForecastEmailRequest) GetUnsubscribeLink() string {
	if x != nil {
		return x.UnsubscribeLink
	}
	return ""
}

// Hourly Forecast Email
type HourlyForecastEmailRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Subscription    *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Weather         *Weather               `protobuf:"bytes,2,opt,name=weather,proto3" json:"weather,omitempty"`
	Date            string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	UnsubscribeLink string                 `protobuf:"bytes,4,opt,name=unsubscribe_link,json=unsubscribeLink,proto3" json:"unsubscribe_link,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HourlyForecastEmailRequest) Reset() {
	*x = HourlyForecastEmailRequest{}
	mi := &file_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HourlyForecastEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HourlyForecastEmailRequest) ProtoMessage() {}

func (x *HourlyForecastEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HourlyForecastEmailRequest.ProtoReflect.Descriptor instead.
func (*HourlyForecastEmailRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{6}
}

func (x *HourlyForecastEmailRequest) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *HourlyForecastEmailRequest) GetWeather() *Weather {
	if x != nil {
		return x.Weather
	}
	return nil
}

func (x *HourlyForecastEmailRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *HourlyForecastEmailRequest) GetUnsubscribeLink() string {
	if x != nil {
		return x.UnsubscribeLink
	}
	return ""
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\fnotification\"N\n" +
	"\fSubscription\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"i\n" +
	"\aWeather\x12 \n" +
	"\vtemperature\x18\x01 \x01(\x02R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x02 \x01(\x02R\bhumidity\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xaa\x02\n" +
	"\n" +
	"DayWeather\x120\n" +
	"\bseven_am\x18\x01 \x01(\v2\x15.notification.WeatherR\asevenAm\x12,\n" +
	"\x06ten_am\x18\x02 \x01(\v2\x15.notification.WeatherR\x05tenAm\x12,\n" +
	"\x06one_pm\x18\x03 \x01(\v2\x15.notification.WeatherR\x05onePm\x12.\n" +
	"\afour_pm\x18\x04 \x01(\v2\x15.notification.WeatherR\x06fourPm\x120\n" +
	"\bseven_pm\x18\x05 \x01(\v2\x15.notification.WeatherR\asevenPm\x12,\n" +
	"\x06ten_pm\x18\x06 \x01(\v2\x15.notification.WeatherR\x05tenPm\"]\n" +
	"\x18ConfirmationEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12+\n" +
	"\x11confirmation_link\x18\x02 \x01(\tR\x10confirmationLink\"&\n" +
	"\n" +
	"SendStatus\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xce\x01\n" +
	"\x19DailyForecastEmailRequest\x12>\n" +
	"\fsubscription\x18\x01 \x01(\v2\x1a.notification.SubscriptionR\fsubscription\x122\n" +
	"\aweather\x18\x02 \x01(\v2\x18.notification.DayWeatherR\aweather\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12)\n" +
	"\x10unsubscribe_link\x18\x04 \x01(\tR\x0funsubscribeLink\"\xcc\x01\n" +
	"\x1aHourlyForecastEmailRequest\x12>\n" +
	"\fsubscription\x18\x01 \x01(\v2\x1a.notification.SubscriptionR\fsubscription\x12/\n" +
	"\aweather\x18\x02 \x01(\v2\x15.notification.WeatherR\aweather\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12)\n" +
	"\x10unsubscribe_link\x18\x04 \x01(\tR\x0funsubscribeLink2\xac\x02\n" +
	"\x13NotificationService\x12Y\n" +
	"\x15SendConfirmationEmail\x12&.notification.ConfirmationEmailRequest\x1a\x18.notification.SendStatus\x12[\n" +
	"\x16SendDailyForecastEmail\x12'.notification.DailyForecastEmailRequest\x1a\x18.notification.SendStatus\x12]\n" +
	"\x17SendHourlyForecastEmail\x12(.notification.HourlyForecastEmailRequest\x1a\x18.notification.SendStatusB/Z-api/proto/stubs/notificationpb;notificationpbb\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_notification_proto_goTypes = []any{
	(*Subscription)(nil),               // 0: notification.Subscription
	(*Weather)(nil),                    // 1: notification.Weather
	(*DayWeather)(nil),                 // 2: notification.DayWeather
	(*ConfirmationEmailRequest)(nil),   // 3: notification.ConfirmationEmailRequest
	(*SendStatus)(nil),                 // 4: notification.SendStatus
	(*DailyForecastEmailRequest)(nil),  // 5: notification.DailyForecastEmailRequest
	(*HourlyForecastEmailRequest)(nil), // 6: notification.HourlyForecastEmailRequest
}
var file_notification_proto_depIdxs = []int32{
	1,  // 0: notification.DayWeather.seven_am:type_name -> notification.Weather
	1,  // 1: notification.DayWeather.ten_am:type_name -> notification.Weather
	1,  // 2: notification.DayWeather.one_pm:type_name -> notification.Weather
	1,  // 3: notification.DayWeather.four_pm:type_name -> notification.Weather
	1,  // 4: notification.DayWeather.seven_pm:type_name -> notification.Weather
	1,  // 5: notification.DayWeather.ten_pm:type_name -> notification.Weather
	0,  // 6: notification.DailyForecastEmailRequest.subscription:type_name -> notification.Subscription
	2,  // 7: notification.DailyForecastEmailRequest.weather:type_name -> notification.DayWeather
	0,  // 8: notification.HourlyForecastEmailRequest.subscription:type_name -> notification.Subscription
	1,  // 9: notification.HourlyForecastEmailRequest.weather:type_name -> notification.Weather
	3,  // 10: notification.NotificationService.SendConfirmationEmail:input_type -> notification.ConfirmationEmailRequest
	5,  // 11: notification.NotificationService.SendDailyForecastEmail:input_type -> notification.DailyForecastEmailRequest
	6,  // 12: notification.NotificationService.SendHourlyForecastEmail:input_type -> notification.HourlyForecastEmailRequest
	4,  // 13: notification.NotificationService.SendConfirmationEmail:output_type -> notification.SendStatus
	4,  // 14: notification.NotificationService.SendDailyForecastEmail:output_type -> notification.SendStatus
	4,  // 15: notification.NotificationService.SendHourlyForecastEmail:output_type -> notification.SendStatus
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
