// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: notification.proto

package notificationpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotificationService_SendConfirmationEmail_FullMethodName   = "/notification.NotificationService/SendConfirmationEmail"
	NotificationService_SendDailyForecastEmail_FullMethodName  = "/notification.NotificationService/SendDailyForecastEmail"
	NotificationService_SendHourlyForecastEmail_FullMethodName = "/notification.NotificationService/SendHourlyForecastEmail"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	SendConfirmationEmail(ctx context.Context, in *ConfirmationEmailRequest, opts ...grpc.CallOption) (*SendStatus, error)
	SendDailyForecastEmail(ctx context.Context, in *DailyForecastEmailRequest, opts ...grpc.CallOption) (*SendStatus, error)
	SendHourlyForecastEmail(ctx context.Context, in *HourlyForecastEmailRequest, opts ...grpc.CallOption) (*SendStatus, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) SendConfirmationEmail(ctx context.Context, in *ConfirmationEmailRequest, opts ...grpc.CallOption) (*SendStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendStatus)
	err := c.cc.Invoke(ctx, NotificationService_SendConfirmationEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SendDailyForecastEmail(ctx context.Context, in *DailyForecastEmailRequest, opts ...grpc.CallOption) (*SendStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendStatus)
	err := c.cc.Invoke(ctx, NotificationService_SendDailyForecastEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) SendHourlyForecastEmail(ctx context.Context, in *HourlyForecastEmailRequest, opts ...grpc.CallOption) (*SendStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendStatus)
	err := c.cc.Invoke(ctx, NotificationService_SendHourlyForecastEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility.
type NotificationServiceServer interface {
	SendConfirmationEmail(context.Context, *ConfirmationEmailRequest) (*SendStatus, error)
	SendDailyForecastEmail(context.Context, *DailyForecastEmailRequest) (*SendStatus, error)
	SendHourlyForecastEmail(context.Context, *HourlyForecastEmailRequest) (*SendStatus, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServiceServer struct{}

func (UnimplementedNotificationServiceServer) SendConfirmationEmail(context.Context, *ConfirmationEmailRequest) (*SendStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendConfirmationEmail not implemented")
}
func (UnimplementedNotificationServiceServer) SendDailyForecastEmail(context.Context, *DailyForecastEmailRequest) (*SendStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDailyForecastEmail not implemented")
}
func (UnimplementedNotificationServiceServer) SendHourlyForecastEmail(context.Context, *HourlyForecastEmailRequest) (*SendStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHourlyForecastEmail not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}
func (UnimplementedNotificationServiceServer) testEmbeddedByValue()                             {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	// If the following call pancis, it indicates UnimplementedNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_SendConfirmationEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmationEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendConfirmationEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SendConfirmationEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendConfirmationEmail(ctx, req.(*ConfirmationEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SendDailyForecastEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DailyForecastEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendDailyForecastEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SendDailyForecastEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendDailyForecastEmail(ctx, req.(*DailyForecastEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_SendHourlyForecastEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HourlyForecastEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).SendHourlyForecastEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_SendHourlyForecastEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).SendHourlyForecastEmail(ctx, req.(*HourlyForecastEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notification.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendConfirmationEmail",
			Handler:    _NotificationService_SendConfirmationEmail_Handler,
		},
		{
			MethodName: "SendDailyForecastEmail",
			Handler:    _NotificationService_SendDailyForecastEmail_Handler,
		},
		{
			MethodName: "SendHourlyForecastEmail",
			Handler:    _NotificationService_SendHourlyForecastEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notification.proto",
}
