name: Tests

on:
  push:
    branches:
      - '**'
      - '!main'

env:
  ENV: "test"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install dependencies
        run: go mod tidy

      # Run Unit tests
      - name: Run unit tests
        run: go test -v $(go list ./ms-notification/... | grep -v 'internal/app\|internal/handlers')
